name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add EC2 to known hosts
        run: |
          ssh-keyscan -H ec2-13-60-27-36.eu-north-1.compute.amazonaws.com >> ~/.ssh/known_hosts

      - name: Connect and Deploy
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@ec2-13-60-27-36.eu-north-1.compute.amazonaws.com "echo '✅ Deployment success!' && uptime"
